apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  labels:
    pswebinar: '21.10'
spec:
  replicas: 4
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
        version: v1
    spec:
      containers:
        - name: app
          image: sixeyed/whoami:21.04