apiVersion: v1
kind: Pod
metadata:
  namespace: rbac-demo
  name: kubectl
spec:
  serviceAccountName: kubectl-sa
  containers:
  - name: app
    image: sixeyed/kubectl:1.21.0
    command: ["sh", "-c", "sleep 30m"]
