apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-web
  labels:
    pswebinar: '21.07'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pi-web
  template:
    metadata:
      labels:
        app: pi-web
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 65534
        runAsGroup: 3000
      containers:
        - image: kiamol/ch05-pi
          command: ["dotnet", "Pi.Web.dll", "-m", "web"]
          name: web
          env:
            - name: ASPNETCORE_URLS
              value: http://+:5001
          ports:
            - containerPort: 5001
              name: http
          resources:
            limits:
              cpu: 250m
            requests:
              cpu: 125m
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
