apiVersion: v1
kind: Service
metadata:
  name: products-api
  namespace: widgetario
spec:
  ports:
    - name: http
      port: 80
      targetPort: api
  selector:
    app: products-api
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api-v1
  namespace: widgetario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-api
      version: v1
  template:
    metadata:
      labels:
        app: products-api
        version: v1
    spec:
      containers:
        - name: api
          image: widgetario/products-api:dotnet
          ports:
            - containerPort: 80
              name: api

