apiVersion: v1
kind: Service
metadata:
  name: stock-api
  namespace: widgetario
spec:
  ports:
    - name: http
      port: 80
      targetPort: api
  selector:
    app: stock-api
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-api
  namespace: widgetario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-api
  template:
    metadata:
      labels:
        app: stock-api
    spec:
      containers:
        - name: api
          image: widgetario/stock-api:dotnet
          ports:
            - containerPort: 80
              name: api

