apiVersion: v1
kind: Service
metadata:
  name: widgetario-web
  namespace: widgetario
spec:
  ports:
    - name: http
      port: 8010
      targetPort: web
  selector:
    app: web
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: widgetario
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: widgetario/web:dotnet
          ports:
            - containerPort: 80
              name: web