apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: products-api
  namespace: widgetario
spec:
  hosts:
    - products-api.widgetario.svc.cluster.local
  http:
  - route:
    - destination:
        host: products-api.widgetario.svc.cluster.local
        subset: v1
      weight: 50
    - destination:
        host: products-api.widgetario.svc.cluster.local
        subset: v2
      weight: 50