apiVersion: v1
kind: ServiceAccount
metadata:
  name: widgetario-web
  namespace: widgetario
  labels:
    account: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: widgetario
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      serviceAccountName: widgetario-web
      containers:
        - name: web
          image: widgetario/web:dotnet
          ports:
            - containerPort: 80
              name: web