apiVersion: v1
kind: ConfigMap
metadata:
  name: configurable-override
data:
  override.json: |-
    {
      "Configurable": {
        "Release": "21.04.03"
      },
      "Features" : {
        "Caching" : true
      }
    }